[project]
name = "torchmamba"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nitg3n", email = "nitg333n@pm.me" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
torchmamba = "torchmamba:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
